import MainLayout from "@/components/layouts";
import { cn } from "@/lib/utils";
import { getWebsite } from "@/services/apis/website";
import "@/styles/index.css";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { bodyFont, headingFont } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

const RootLayout = async (props: Props) => {
  const websiteResponse = await getWebsite();

  if (!websiteResponse.data) {
    throw new Error("Failed to fetch website data");
  }

  const { children } = props;

  return (
    <html lang="en">
      <body
        className={cn(headingFont.variable, bodyFont.variable, "antialiased")}
      >
        <MainLayout website={websiteResponse.data}>{children}</MainLayout>
      </body>
    </html>
  );
};

export default RootLayout;
