import { cn } from "@/lib/utils";
import "@/styles/index.css";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { bodyFont, headingFont } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

const RootLayout = (props: Props) => {
  const { children } = props;

  return (
    <html lang="en">
      <body
        className={cn(headingFont.variable, bodyFont.variable, "antialiased")}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
